/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Extended modal logic with 4-valued semantics, now including a `val` constructor
for applying the valuation function to complex formulas, and T(T(P)) results.
Generalized to n-fold iteration Tⁿ(P) with inductive satisfiability proof.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped Classical

set_option maxHeartbeats 800000
set_option maxRecDepth 4000

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-! ## Four-valued type and formula language -/

inductive Val4
| t | f | b | n
deriving DecidableEq, Repr

inductive Formula (P : Type)
| atom (p : P) (v : Val4) : Formula P
| not (φ : Formula P) : Formula P
| and (φ ψ : Formula P) : Formula P
| box (φ : Formula P) : Formula P
| val (φ : Formula P) (v : Val4) : Formula P

structure Model (W : Type) (P : Type) where
  R : W → W → Prop
  V : P → W → Val4

/-! ## Satisfaction relation

The `val` constructor extends satisfaction:
- `val φ t` holds iff `φ` is satisfied
- `val φ f` holds iff `φ` is not satisfied
- `val φ b` never holds at any world
- `val φ n` never holds at any world
-/

def satisfies {W P : Type} (M : Model W P) (w : W) : Formula P → Prop
| Formula.atom _p v => M.V _p w = v
| Formula.not φ => ¬ satisfies M w φ
| Formula.and φ ψ => satisfies M w φ ∧ satisfies M w ψ
| Formula.box φ => ∀ w', M.R w w' → satisfies M w' φ
| Formula.val φ Val4.t => satisfies M w φ
| Formula.val φ Val4.f => ¬ satisfies M w φ
| Formula.val _ Val4.b => False
| Formula.val _ Val4.n => False

/-! ## Atoms -/

inductive Atom | P deriving DecidableEq, Repr

/-! ## Target formula T(P)

T(P) = ¬□(v(P)=t) ∧ ¬□(v(P)=f) ∧ ¬□(v(P)=b) ∧ ¬□(v(P)=n)
-/

def target_formula : Formula Atom :=
  Formula.and
    (Formula.and
      (Formula.and
        (Formula.not (Formula.box (Formula.atom Atom.P Val4.t)))
        (Formula.not (Formula.box (Formula.atom Atom.P Val4.f))))
      (Formula.not (Formula.box (Formula.atom Atom.P Val4.b))))
    (Formula.not (Formula.box (Formula.atom Atom.P Val4.n)))

/-! ## T(T(P)): the four-fold negated-box conjunction asserting T(P) has no necessary truth value

T(T(P)) = ¬□(val(T(P)) = t) ∧ ¬□(val(T(P)) = f) ∧ ¬□(val(T(P)) = b) ∧ ¬□(val(T(P)) = n)

Uses the `val` constructor to assert things about the complex formula T(P).
-/

def target_target_formula : Formula Atom :=
  Formula.and
    (Formula.and
      (Formula.and
        (Formula.not (Formula.box (Formula.val target_formula Val4.t)))
        (Formula.not (Formula.box (Formula.val target_formula Val4.f))))
      (Formula.not (Formula.box (Formula.val target_formula Val4.b))))
    (Formula.not (Formula.box (Formula.val target_formula Val4.n)))

/-! ## K model

We use `Fin 7` with the following structure:
- `0` (w₀): the evaluation world
- `1` (w_good): has four successors with all four values, so T(P) holds here
- `2` (w_bad): has no successors, so all boxes are vacuously true and T(P) fails
- `3,4,5,6`: successors of w_good with values t, f, b, n respectively

From w₀, the accessible worlds are w_good (1) and w_bad (2).
This ensures:
- T(P) at w₀: for each value v, some successor of w₀ has V(P) ≠ v
- T(T(P)) at w₀: w_good satisfies T(P) (witness for ¬□(val(T(P))=f)),
                   w_bad does not satisfy T(P) (witness for ¬□(val(T(P))=t)),
                   both are accessible (witnesses for b and n conjuncts)
-/

def R_K (x y : Fin 7) : Prop :=
  (x = 0 ∧ (y = 1 ∨ y = 2)) ∨
  (x = 1 ∧ (y = 3 ∨ y = 4 ∨ y = 5 ∨ y = 6))

def V_K (_p : Atom) (w : Fin 7) : Val4 :=
  if w = 1 then Val4.t
  else if w = 2 then Val4.f
  else if w = 3 then Val4.t
  else if w = 4 then Val4.f
  else if w = 5 then Val4.b
  else if w = 6 then Val4.n
  else Val4.t

def M_K : Model (Fin 7) Atom :=
  { R := R_K, V := V_K }

/-! ## Theorem 1: T(P) is satisfiable at w₀ in the K model -/

theorem satisfies_K : satisfies M_K (0 : Fin 7) target_formula := by
  unfold target_formula; simp +decide [satisfies]
  unfold M_K; simp +decide [R_K, V_K]

/-! ## Theorem 2: T(T(P)) is satisfiable at w₀ in the K model -/

/-- At world 1 (w_good), T(P) holds because it has successors 3,4,5,6
    with all four values. -/
theorem satisfies_TP_at_wgood : satisfies M_K (1 : Fin 7) target_formula := by
  unfold target_formula
  simp +decide [satisfies]
  unfold M_K; simp +decide [R_K]

/-- At world 2 (w_bad), T(P) does NOT hold because it has no successors,
    so □(atom P t) is vacuously true, making ¬□(atom P t) false. -/
theorem not_satisfies_TP_at_wbad : ¬ satisfies M_K (2 : Fin 7) target_formula := by
  unfold target_formula; simp +decide [satisfies]
  simp +decide [M_K, R_K, V_K]

theorem satisfies_K_TTP : satisfies M_K (0 : Fin 7) target_target_formula := by
  unfold target_target_formula
  simp +decide [satisfies] at *
  unfold M_K; simp +decide [R_K]
  exact ⟨Or.inr not_satisfies_TP_at_wbad, Or.inl satisfies_TP_at_wgood⟩

/-! ## Theorem 3: The b and n conjuncts

`val φ b` and `val φ n` never hold at any world in any model, so the
negated-box conjuncts for b and n are trivially true (given accessible worlds exist).
-/

/-- `val φ b` is never satisfied at any world in any model. -/
theorem val_b_never {W P : Type} {M : Model W P} {w : W} {φ : Formula P} :
    ¬ satisfies M w (Formula.val φ Val4.b) :=
  Not.imp (fun a => a) fun a => a

/-- `val φ n` is never satisfied at any world in any model. -/
theorem val_n_never {W P : Type} {M : Model W P} {w : W} {φ : Formula P} :
    ¬ satisfies M w (Formula.val φ Val4.n) := by
  simp [satisfies]

/-- If `w` has at least one accessible world, then `¬□(val φ b)` holds trivially,
    because `val φ b` is never satisfied at any world. -/
theorem box_val_b_trivial {W P : Type} {M : Model W P} {w : W} {φ : Formula P}
    (h : ∃ w', M.R w w') :
    satisfies M w (Formula.not (Formula.box (Formula.val φ Val4.b))) := by
  unfold satisfies; aesop

/-- If `w` has at least one accessible world, then `¬□(val φ n)` holds trivially,
    because `val φ n` is never satisfied at any world. -/
theorem box_val_n_trivial {W P : Type} {M : Model W P} {w : W} {φ : Formula P}
    (h : ∃ w', M.R w w') :
    satisfies M w (Formula.not (Formula.box (Formula.val φ Val4.n))) := by
  obtain ⟨w', hw'⟩ := h
  simp [satisfies]
  use w'

/-! ## N-fold catuskoti operator -/

/-- The catuskoti operator T: applies the four-fold negated-box conjunction using the val constructor.
    T(φ) asserts that φ has no definite truth value across accessible worlds. -/
def T_apply (φ : Formula Atom) : Formula Atom :=
  Formula.and
    (Formula.and
      (Formula.and
        (Formula.not (Formula.box (Formula.val φ Val4.t)))
        (Formula.not (Formula.box (Formula.val φ Val4.f))))
      (Formula.not (Formula.box (Formula.val φ Val4.b))))
    (Formula.not (Formula.box (Formula.val φ Val4.n)))

/-- n-fold iteration of T. T_iter 0 is the atom for P (the base proposition).
    T_iter (n+1) = T(T_iter n), applying the catuskoti operator. -/
def T_iter : ℕ → Formula Atom
| 0 => Formula.atom Atom.P Val4.t
| (n + 1) => T_apply (T_iter n)

/-- T_apply applied to target_formula yields target_target_formula. -/
theorem T_apply_target_eq : T_apply target_formula = target_target_formula := rfl

/-! ## Disjoint union model construction

To prove satisfiability of T_apply(φ), we combine two models:
one where φ holds and one where φ fails, joining them at a fresh root world.
Satisfaction is preserved within each component, ensuring the root sees
both a world satisfying φ and one refuting it.
-/

/-- Combined model: two Kripke models joined at a fresh root world.
    The root sees exactly w₁ from M₁ and w₂ from M₂.
    Within each component, accessibility is inherited from the original model. -/
def combined_model {W₁ W₂ : Type} (M₁ : Model W₁ Atom) (M₂ : Model W₂ Atom)
    (w₁ : W₁) (w₂ : W₂) : Model (Option (W₁ ⊕ W₂)) Atom where
  R x y := match x, y with
    | none, some (Sum.inl a) => a = w₁
    | none, some (Sum.inr b) => b = w₂
    | some (Sum.inl a), some (Sum.inl b) => M₁.R a b
    | some (Sum.inr a), some (Sum.inr b) => M₂.R a b
    | _, _ => False
  V p w := match w with
    | none => Val4.t
    | some (Sum.inl a) => M₁.V p a
    | some (Sum.inr b) => M₂.V p b

/-- Satisfaction is preserved when embedding into the left component of a combined model. -/
theorem satisfies_combined_left {W₁ W₂ : Type} {M₁ : Model W₁ Atom} {M₂ : Model W₂ Atom}
    {w₁ : W₁} {w₂ : W₂} (φ : Formula Atom) (a : W₁) :
    satisfies (combined_model M₁ M₂ w₁ w₂) (some (Sum.inl a)) φ ↔ satisfies M₁ a φ := by
  induction' φ with φ ψ ihφ ihψ generalizing a;
  · rfl;
  · simp +decide [ *, satisfies ];
  · simp_all +decide [ satisfies ];
  · simp +decide [ *, satisfies ];
    constructor <;> intro h w' hw';
    · specialize h ( some ( Sum.inl w' ) ) ; aesop;
    · rcases w' with ( _ | _ | w' ) <;> simp_all +decide [ combined_model ];
  · cases ‹Val4› <;> simp_all +decide [ satisfies ]

/-- Satisfaction is preserved when embedding into the right component of a combined model. -/
theorem satisfies_combined_right {W₁ W₂ : Type} {M₁ : Model W₁ Atom} {M₂ : Model W₂ Atom}
    {w₁ : W₁} {w₂ : W₂} (φ : Formula Atom) (b : W₂) :
    satisfies (combined_model M₁ M₂ w₁ w₂) (some (Sum.inr b)) φ ↔ satisfies M₂ b φ := by
  induction' φ with _ _ _ _ _ _ _ _ ih generalizing b;
  · aesop;
  · simp_all +decide [ satisfies ];
  · simp_all +decide [ satisfies ];
  · simp_all +decide [ satisfies ];
    constructor;
    · intro h w' hw'; specialize h ( some ( Sum.inr w' ) ) ; aesop;
    · intro h w' hw'; rcases w' with ( _ | ⟨ _ | w' ⟩ ) <;> simp_all +decide [ combined_model ] ;
  · rename_i φ v ih;
    cases v <;> simp +decide [ *, satisfies ]

/-! ## Refutability of T_iter -/

/-- A model on Unit with no accessibility and V(P) = f. Used to refute formulas
    containing negated-box conjuncts. -/
def trivial_model : Model Unit Atom where
  R _ _ := False
  V _ _ := Val4.f

/-- Any T_iter n is refutable: there exists a model and world where it fails.
    For n = 0: atom P t fails when V(P) = f.
    For n ≥ 1: T_apply always contains ¬□(val _ b), which requires an accessible world,
    so it fails at any isolated world. -/
theorem T_iter_refutable (n : ℕ) :
    ∃ (W : Type) (M : Model W Atom) (w : W), ¬ satisfies M w (T_iter n) := by
  -- Use the type `Unit` for the world, as there is only one world in the trivial model.
  use Unit, trivial_model, ();
  induction' n with n ih <;> simp_all +decide [ T_iter ];
  · -- By definition of `trivial_model`, we know that `V(P) = f`.
    simp [satisfies, trivial_model];
  · unfold T_apply; simp +decide [ ih, satisfies ] ;

/-! ## Main satisfiability theorem -/

/-- If φ is both satisfiable and refutable, then T_apply(φ) is satisfiable.
    This is the key inductive step: we build a combined model with a root that sees
    one world where φ holds (refuting □(val φ f)) and one where it doesn't
    (refuting □(val φ t)). The b and n conjuncts are trivially satisfied
    since val _ b and val _ n are always false. -/
theorem T_apply_satisfiable (φ : Formula Atom)
    (hsat : ∃ (W : Type) (M : Model W Atom) (w : W), satisfies M w φ)
    (href : ∃ (W : Type) (M : Model W Atom) (w : W), ¬ satisfies M w φ) :
    ∃ (W : Type) (M : Model W Atom) (w : W), satisfies M w (T_apply φ) := by
  -- Use the Test model to satisfy T(φ).
  use Option (hsat.choose ⊕ href.choose), combined_model hsat.choose_spec.choose href.choose_spec.choose hsat.choose_spec.choose_spec.choose href.choose_spec.choose_spec.choose, none;
  -- By definition of combined_model, we need to show that the four conjuncts of T_apply φ hold at the root.
  simp [T_apply, satisfies];
  refine' ⟨ ⟨ _, _ ⟩, _ ⟩;
  · use some (Sum.inr href.choose_spec.choose_spec.choose);
    exact ⟨ by tauto, by simpa using satisfies_combined_right φ _ |>.not.mpr href.choose_spec.choose_spec.choose_spec ⟩;
  · use some (Sum.inl hsat.choose_spec.choose_spec.choose);
    exact ⟨ by tauto, by simpa using satisfies_combined_left φ _ |>.2 hsat.choose_spec.choose_spec.choose_spec ⟩;
  · exact ⟨ some ( Sum.inl hsat.choose_spec.choose_spec.choose ), by tauto ⟩

/-- **Main theorem**: For all n, Tⁿ(P) is satisfiable.
    - Base case (n = 0): atom P t is satisfied by any world where V(P) = t.
    - Inductive step: T_iter n is satisfiable (IH) and refutable (T_iter_refutable),
      so T_apply_satisfiable gives satisfiability of T_iter (n+1). -/
theorem T_iter_satisfiable : ∀ n : ℕ,
    ∃ (W : Type) (M : Model W Atom) (w : W), satisfies M w (T_iter n) := by
  intro n
  induction n with
  | zero =>
    exact ⟨Unit, ⟨fun _ _ => False, fun _ _ => Val4.t⟩, (), rfl⟩
  | succ n ih =>
    exact T_apply_satisfiable (T_iter n) ih (T_iter_refutable n)

end
